### ISSUE TITLE
Exception Error , Any Solution ?

### ISSUE THREAD

**Issue by arbazkiraak** [ajinabraham/Node.Js-Security-Course#1]
root@arbaz:~/Desktop/NodeJsScan# python NodeJsScan.py -d Node.Js-Security-Course/

NodeJsScan is a node.js Static Analysis Tool that can detect possible security issues, insecure code and outdated libraries (using retire.js).

Running Static Analyzer Running on - Node.Js-Security-Course/

Traceback (most recent call last):
  File "NodeJsScan.py", line 184, in <module>
    main()
  File "NodeJsScan.py", line 171, in main
    dat,sec, out=NodeJSStaticAnalyzer(options.dir,True)
  File "NodeJsScan.py", line 31, in NodeJSStaticAnalyzer
    with open(jfile_path,'r') as f:
IOError: [Errno 2] No such file or directory: 'Node.Js-Security-Course/Node.Js-Security-Course/global_scope.js'

Kali Linux 2.0 , Python2.7 ,        Node.Js-Security-Course/ is the Directory Which Contains All Nodejs Vuln Files in Same Directory of tool

**Comment by arbazkiraak** [comment]
Closing As Resolved ,
